/**流程分类 */
export const REQUEST_CATEGORY = "REQUEST_CATEGORY";
export const CATEGORY_LOADED = "CATEGORY_LOADED";

/**Admin流程分类 */
export const REQUEST_ADMIN_CATEGORY = "REQUEST_ADMIN_CATEGORY";
export const ADMIN_CATEGORY_LOADED = "ADMIN_CATEGORY_LOADED";

/**任务数量 */
export const REQUEST_TASKCOUNT = "REQUEST_TASKCOUNT";
export const TASK_COUNTLOADED = "TASK_COUNTLOADED";

/*绩效报表模块创建时间*/
export const REQUEST_MOUDLEDATE = "REQUEST_MOUDLEDATE";
export const MOUDLEDATE_LOADED = "MOUDLEDATE_LOADED";

/*根据listdataid获取project列表的数据*/
export const REQUESTROJECT_LISTDATA = "REQUESTROJECT_LISTDATA";
export const GETPROJECT_LISTDATA = "GETPROJECT_LISTDATA";

/**AIIB是否在 administrator组内*/
export const ISAIIB_ADMINISTRATOR = "ISAIIB_ADMINISTRATOR";
export const REQUESRAIIB_ROLE = "REQUESRAIIB_ROLE";

